steps:
  - label: ":running: oss unit test"
    timeout: 3600
    env:
      COMMAND: "bash .buildkite/ci/build_editable.sh && bash .buildkite/ci/run_unit_test.sh"
      COMPUTE_CONFIG: ".buildkite/ci/compute-config-g5-2xlarge.yaml"
    commands:
      - bash .buildkite/job_submit_buildkite.sh
    retry:
      automatic:
        - exit_status: -1 # Agent lost/spot preemption
          limit: 2

  # - label: ":running: spec decode tp1 tests"
  #   timeout: 7200
  #   env:
  #     COMMAND: "bash .buildkite/ci/build_editable.sh && bash .buildkite/ci/run_spec_decode_tp1_test.sh"
  #     COMPUTE_CONFIG: ".buildkite/ci/compute-config-g5-2xlarge.yaml"
  #   commands:
  #     - bash .buildkite/job_submit_buildkite.sh
  #   retry:
  #     automatic:
  #       - exit_status: -1 # Agent lost/spot preemption
  #         limit: 2

  # - label: ":running: kernel tests"
  #   timeout: 7200
  #   env:
  #     COMMAND: "bash .buildkite/ci/build_editable.sh && bash .buildkite/ci/run_kernel_tests.sh"
  #     COMPUTE_CONFIG: ".buildkite/ci/compute-config-g5-2xlarge.yaml"
  #   commands:
  #     - bash .buildkite/job_submit_buildkite.sh
  #   retry:
  #     automatic:
  #       - exit_status: -1 # Agent lost/spot preemption
  #         limit: 2

  # - label: ":running: s3 test"
  #   timeout: 1800
  #   env:
  #     COMMAND: "BUILD_BAZEL=1 bash .buildkite/ci/build_editable.sh && bash .buildkite/ci/run_s3_test.sh"
  #     COMPUTE_CONFIG: ".buildkite/ci/compute-config-g5-2xlarge.yaml"
  #   commands:
  #     - bash .buildkite/job_submit_buildkite.sh
  #   retry:
  #     automatic:
  #       - exit_status: -1 # Agent lost/spot preemption
  #         limit: 2

  # - label: ":running: distributed test"
  #   timeout: 3600
  #   env:
  #     COMMAND: "bash .buildkite/ci/build_editable.sh && bash .buildkite/ci/run_distributed_test.sh"
  #     COMPUTE_CONFIG: ".buildkite/ci/compute-config-g5-12xlarge.yaml"
  #   commands:
  #     - bash .buildkite/job_submit_buildkite.sh
  #   retry:
  #     automatic:
  #       - exit_status: -1 # Agent lost/spot preemption
  #         limit: 2

  # - label: ":running: correctness test"
  #   timeout: 3600
  #   env:
  #     COMMAND: "bash .buildkite/ci/build_editable.sh && bash .buildkite/ci/run_correctness_test.sh"
  #     COMPUTE_CONFIG: ".buildkite/ci/compute-config-g5-2xlarge.yaml"
  #   commands:
  #     - bash .buildkite/job_submit_buildkite.sh
  #   retry:
  #     automatic:
  #       - exit_status: -1 # Agent lost/spot preemption
  #         limit: 2

  - label: ":python: build wheel"
    timeout: 1800
    key: "build_wheel"
    env:
      COMMAND: "bash .buildkite/ci/build_wheel.sh"
      COMPUTE_CONFIG: ".buildkite/ci/compute-config-m5-8xlarge.yaml"
      # Uses ubunt 22.04.
      IMAGE: anyscale/ray:2.12.0-py39-cu121
    commands:
      - bash .buildkite/job_submit_buildkite.sh
    retry:
      automatic:
        - exit_status: -1 # Agent lost/spot preemption
          limit: 2
