cloud: aviary-prod
region: us-west-2
head_node_type:
  name: head-node-m5
  instance_type: m5.8xlarge
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      head_node: 1
worker_node_types: []
maximum_uptime_minutes: 120