cloud: aviary-prod
region: us-west-2
head_node_type:
  name: head-node-g4
  instance_type: g4dn.12xlarge
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      head_node: 1
      accelerator_type_a10: 1
  aws_advanced_configurations_json:
    TagSpecifications:
      - ResourceType: instance
        Tags:
          - Key: as-feature-customized-alternates
            Value: $g4dn.12xlarge
worker_node_types: []
maximum_uptime_minutes: 180